import json,fitz
from pathlib import Path
p=Path(__file__).parent
items=json.loads((p/'batch05_prepared.json').read_text())
data={
'Temel_Matematik-22':('Şifreyi seçme ve yerleştirme olarak iki adımda sayalım. Artan sıra şartıyla iki farklı rakam seçiyoruz. Altı rakamdan ikisini seçmenin sayısı, altı çarpı beş bölü iki, on beştir. Dört harften iki farklı harf seçmenin sayısı, dört çarpı üç bölü iki, altıdır. Şimdi dört konumdan rakamların duracağı iki konumu seçelim; bunun da altı yolu var. Seçilen rakamlar kendi aralarında küçükten büyüğe, harfler kendi aralarında alfabetik sıraya gireceği için ayrıca permütasyonla çarpmıyoruz. On beş çarpı altı çarpı altı, beş yüz kırk şifre eder. E seçeneğini işaretliyoruz.', [('Rakam seçimi: 6×5/2=15','Altı rakamdan ikisini seçmenin sayısı, altı çarpı beş bölü iki, on beştir'),('Harf seçimi: 4×3/2=6','Dört harften iki farklı harf seçmenin sayısı, dört çarpı üç bölü iki, altıdır'),('Rakamların yerleri: 6','dört konumdan rakamların duracağı iki konumu seçelim; bunun da altı yolu var'),('15×6×6=540','On beş çarpı altı çarpı altı, beş yüz kırk şifre eder')]),
'Fen_Bilimleri-06':('Özdeş, ideal pillerin her birinin gerilimine ve diyelim. Birinci devrede seri bağlandıkları için toplam gerilim iki ve olur. Direnç aynı olduğundan birinci devrenin akımı, iki ve bölü re olur. Ka pili bu akımın tamamını verir. İkinci devrede piller paraleldir; direnç üzerindeki gerilim ve, toplam akım ve bölü redir. Özdeş piller bu akımı eşit paylaşır. Le pilinden geçen akım, ve bölü iki redir. Böylece birinci devrenin direnç gerilimi daha büyük, ka pilinin akımı da daha büyüktür. Aynı kapasiteli le pili daha az akım verdiği için daha uzun süre dayanır. Üç yargı da doğrudur; E seçeneğini işaretliyoruz.', [('Seri: 2V; paralel: V','Birinci devrede seri bağlandıkları için toplam gerilim iki ve olur'),('K akımı: 2V/R','birinci devrenin akımı, iki ve bölü re olur'),('L akımı: V/(2R)','Le pilinden geçen akım, ve bölü iki redir'),('L daha uzun dayanır','le pili daha az akım verdiği için daha uzun süre dayanır')]),
'Fen_Bilimleri-07':('Dalgaları yayılmak için maddesel ortama ihtiyaç duyup duymamalarına göre ayırıyoruz. Su ve deprem dalgaları mekanik dalgalardır; ortamın titreşimleriyle yayılırlar. Yay dalgası da yayın titreşimiyle iletilir, yani mekaniktir. Tabloda yay dalgası elektromanyetik sütununa yazıldığı için hata buradadır. Radyo ve kızılötesi dalgalar ise elektromanyetiktir; boşlukta da yayılabilirler. Yanlış sınıflandırılan yay dalgasını veren E seçeneğini işaretliyoruz.', [('Mekanik: maddesel ortam','Su ve deprem dalgaları mekanik dalgalardır'),('Yay da mekaniktir','Yay dalgası da yayın titreşimiyle iletilir, yani mekaniktir'),('Radyo ve kızılötesi: EM','Radyo ve kızılötesi dalgalar ise elektromanyetiktir')]),
'Fen_Bilimleri-10':('Periyodik tablodaki yerlerinden elementleri tanıyalım. İks magnezyum, ye alüminyum, ze flordur. İksin değerlik elektron sayısı iki, yenin üç, zenin yedidir. İki ile üçün toplamı beştir; yedi etmez. Bu nedenle E seçeneğindeki eşitlik yanlıştır. Diğer bilgileri de kontrol edelim. Bu üçlüde atom yarıçapı ve metalik etkinliği en büyük olan magnezyum, elektronegatifliği en büyük olan flordur. İlk iyonlaşma enerjisinde ise magnezyumun dolu üç es alt kabuğu nedeniyle alüminyumdan yüksek olduğu istisnayı hatırlamalıyız. Yanlış ifade istendiğinden E seçeneğini işaretliyoruz.', [('X: Mg; Y: Al; Z: F','İks magnezyum, ye alüminyum, ze flordur'),('Değerlik: 2,3,7','İksin değerlik elektron sayısı iki, yenin üç, zenin yedidir'),('2+3=5 ≠ 7','İki ile üçün toplamı beştir; yedi etmez')]),
'Fen_Bilimleri-12':('Sorunun eş koşullu akış deneyini karşılaştıralım. İks sıvısı otuz, ye sıvısı yirmi saniyede akıyor. İks akmaya daha fazla direnç gösterdiği için viskozitesi daha büyük kabul edilir. Bu okul düzeyi karşılaştırmada, moleküller arası çekimi daha güçlü olan sıvı ikstir; birinci yargı doğrudur. Yenin viskozitesinin daha yüksek olduğunu söyleyen ikinci yargı tersini söylüyor, yanlıştır. Bir sıvıyı soğutmak genellikle viskozitesini artırır. İksi soğutmak, zaten daha küçük viskoziteli olan yeye yaklaştırmaz. Üçüncü yargı da yanlıştır. Yalnız birinciyi veren A seçeneğini işaretliyoruz.', [('Akış: X 30s; Y 20s','İks sıvısı otuz, ye sıvısı yirmi saniyede akıyor'),('Viskozite: X>Y','viskozitesi daha büyük kabul edilir'),('Soğutma → viskozite artar','Bir sıvıyı soğutmak genellikle viskozitesini artırır')]),
'Fen_Bilimleri-13':('Hacimleri karşılaştırmak için ideal gaz bağıntısını kullanalım. Basınç çarpı hacim, mol sayısı çarpı gaz sabiti çarpı mutlak sıcaklıktır. Hacim için mol sayısıyla sıcaklığı çarpıp basınca böleriz. Gaz sabiti hepsinde aynı olduğu için sıralamada sadeleşir. İks için sıfır virgül beş çarpı yüz bölü üç, elli bölü üç çıkar. Ye için bir çarpı üç yüz bölü iki, yüz ellidir. Ze için bir buçuk çarpı iki yüz bölü bir, üç yüzdür. En büyük hacim ze, sonra ye, en küçük ikstir. B seçeneğini işaretliyoruz.', [('V=nRT/P','Hacim için mol sayısıyla sıcaklığı çarpıp basınca böleriz'),('X: 0,5×100/3=50/3','İks için sıfır virgül beş çarpı yüz bölü üç, elli bölü üç çıkar'),('Y: 150; Z: 300','Ye için bir çarpı üç yüz bölü iki, yüz ellidir. Ze için bir buçuk çarpı iki yüz bölü bir, üç yüzdür'),('VZ>VY>VX','En büyük hacim ze, sonra ye, en küçük ikstir')]),
'Fen_Bilimleri-14':('Üç kapta sıcaklık, su miktarı ve şeker kütlesi aynı. Değişen özellik şekerin tanecik boyutudur. Tanecikler küçüldükçe suyla temas eden toplam yüzey büyür ve çözünme hızlanır. Pudra şekerinin yüzeyi en büyük olduğu için ikinci kap en hızlıdır. Toz şeker bulunan birinci kap onu izler. Küp şeker bulunan üçüncü kap en yavaştır. Çözünme miktarıyla çözünme hızını karıştırmayalım; burada sorulan hızdır. Sıralama ikinci, birinci, üçüncü olur. C seçeneğini işaretliyoruz.', [('Küçük tanecik → büyük yüzey','Tanecikler küçüldükçe suyla temas eden toplam yüzey büyür'),('Pudra > toz > küp','Pudra şekerinin yüzeyi en büyük olduğu için ikinci kap en hızlıdır'),('Hız: II>I>III','Sıralama ikinci, birinci, üçüncü olur')]),
'Fen_Bilimleri-16':('Tanımdaki belirleyici koşula dikkat edelim: doğal ortamda çiftleşip, kendileri de üreyebilen yavrular oluşturmak. Bu, biyolojik tür tanımına karşılık gelir. Yalnız dış görünüş benzerliği yeterli değildir; verimli döl oluşturabilme koşulu da aranır. Cins, aile, takım ve sınıf daha geniş sınıflandırma basamaklarıdır. Soruda verilen en özel birim türdür. C seçeneğini işaretliyoruz.', [('Doğal koşullarda çiftleşme','doğal ortamda çiftleşip'),('Verimli döl','kendileri de üreyebilen yavrular oluşturmak'),('Biyolojik tür','Bu, biyolojik tür tanımına karşılık gelir')]),
'Fen_Bilimleri-17':('Nişasta, glikojen ve selülozun üçü de polisakkarittir. Ortak yapı taşları glikozdur. Çok sayıda glikoz, glikozit bağlarıyla birleşerek bu büyük molekülleri oluşturur. B seçeneği bu ortak özelliği söylüyor. İşlevleri ise aynı değildir: nişasta ve glikojen depo maddeleriyken, selüloz bitki hücre duvarında yapıya katılır. İnsan selülozu kendi sindirim enzimleriyle parçalayamaz. Bu nedenle depolama, bitkide üretilme veya insanda sindirilme özelliklerini üçünün ortak özelliği sayamayız. B seçeneğini işaretliyoruz.', [('Üçü de polisakkarit','Nişasta, glikojen ve selülozun üçü de polisakkarittir'),('Glikoz + glikozit bağları','Çok sayıda glikoz, glikozit bağlarıyla birleşerek bu büyük molekülleri oluşturur'),('Selüloz: yapı maddesi','selüloz bitki hücre duvarında yapıya katılır')]),
'Fen_Bilimleri-18':('Geviş getirenlerde sindirimi hayvanın kendi enzimleriyle, birlikte yaşayan mikroorganizmaların katkısını ayırarak değerlendirelim. Mide dört özelleşmiş bölümden oluşabilir; birinci yargı doğrudur. Selülozu parçalayan enzimleri hayvanın kendi hücreleri üretmez. Sindirim sistemindeki ortak yaşayan mikroorganizmalar üretir. Bu yüzden ikinci yargı, enzimi hayvana atfettiği biçimiyle yanlıştır. Yutulmuş besini ağza geri getirip yeniden çiğnemek geviş getirmedir; üçüncü yargı doğrudur. Birinci ve üçüncüyü veren C seçeneğini işaretliyoruz.', [('I: dört bölümlü mide','Mide dört özelleşmiş bölümden oluşabilir'),('Selülaz: mikroorganizmalar','Sindirim sistemindeki ortak yaşayan mikroorganizmalar üretir'),('III: yeniden çiğneme','Yutulmuş besini ağza geri getirip yeniden çiğnemek geviş getirmedir')]),
'Fen_Bilimleri-19':('Kemosentezde organik madde üretimi için ışık yerine kimyasal tepkimelerden sağlanan enerji kullanılır. Nitrifikasyon bakterileri inorganik azot bileşiklerini yükseltgerken enerji elde edebilir. Bu enerjiyi organik madde sentezinde kullanmaları kemosentezdir. Yeşil algler, siyanobakteriler ve öglena fotosentez yaparken ışık enerjisini kullanır. Mantarlar ise hazır organik besin alır. Seçenekler içinde kemosentez yapabilen grup nitrifikasyon bakterileridir. E seçeneğini işaretliyoruz.', [('Kemosentez: kimyasal enerji','ışık yerine kimyasal tepkimelerden sağlanan enerji kullanılır'),('Nitrifikasyon bakterileri','Nitrifikasyon bakterileri inorganik azot bileşiklerini yükseltgerken enerji elde edebilir'),('Enerji → organik madde','Bu enerjiyi organik madde sentezinde kullanmaları kemosentezdir')]),
'Fen_Bilimleri-20':('İki canlı üzerindeki etkiyi ayrı ayrı yazalım. Kuşlar kaçışan böcekleri kolay yakaladıkları için yarar görüyor; kuşlara artı işareti verelim. Metin sığırların ne yarar ne zarar gördüğünü açıkça söylüyor; sığırlar için sıfır yazalım. Bir türün yarar gördüğü, diğerinin etkilenmediği artı sıfır ilişkisi kommensalizmdir. Mutualizmde iki tür de yarar görürdü; parazitizmde ise birinin yararına karşılık diğeri zarar görürdü. Sorudaki ilişkiyi veren D seçeneğini işaretliyoruz.', [('Kuş: +','kuşlara artı işareti verelim'),('Sığır: 0','sığırlar için sıfır yazalım'),('(+ , 0) → kommensalizm','artı sıfır ilişkisi kommensalizmdir')]),
'Sosyal_Bilimler-09':('İkincil ekonomik sektörde ham madde işlenir veya yapı inşa edilir. Pamuğun iplik ve kumaşa dönüştürülmesi sanayi faaliyetidir; ikinci örnek bu sektöre girer. Konut, köprü ve yol yapımı da inşaat faaliyetidir; üçüncü örnek de ikincil sektördedir. Ürünlerin tüketiciye ulaştırılıp satılması ise ticaret ve dağıtım hizmetidir, üçüncül sektöre girer. Dolayısıyla ikinci ve üçüncü örnekleri seçmeliyiz. E seçeneğini işaretliyoruz.', [('II: işleme → sanayi','Pamuğun iplik ve kumaşa dönüştürülmesi sanayi faaliyetidir'),('III: yapı → inşaat','Konut, köprü ve yol yapımı da inşaat faaliyetidir'),('I: ticaret → üçüncül','Ürünlerin tüketiciye ulaştırılıp satılması ise ticaret ve dağıtım hizmetidir')]),
'Sosyal_Bilimler-10':('Şeklin üç aşamasını izleyelim. Önce su, kayacın çatlaklarından yer altına sızıyor. Çözünebilen kayacı aşındırarak yer altında boşluklar oluşturuyor. Boşluk büyüdüğünde tavanı taşıyamıyor ve çökme gerçekleşiyor. Yüzeyde oluşan derin çukur, çökme kökenli bir obruk. Traverten birikme şeklidir; burada ise çözünme ve çökme var. Düden suyun yer altına geçtiği yeri anlatır; şekilde özellikle tavanın çökmesi gösterilmiş. Obruğu veren A seçeneğini işaretliyoruz.', [('1: sızma','su, kayacın çatlaklarından yer altına sızıyor'),('2: çözünme ve boşluk','Çözünebilen kayacı aşındırarak yer altında boşluklar oluşturuyor'),('3: çökme → obruk','Yüzeyde oluşan derin çukur, çökme kökenli bir obruk')]),
'Sosyal_Bilimler-12':('Parçanın temel vurgusu, evrendeki varlıkların sürekli değişmesidir. Nehir örneğinde suyun akıp gitmesi, hiçbir şeyin aynı biçimde kalmamasını açıklıyor. Herakleitos için varlık durağan bir şey olarak değil, oluş ve değişme süreci olarak ele alınıyor. Bu görüşe oluşçuluk denir. Parça bilginin kuşkulu oluşunu ya da hiçbir şeyin var olmadığını savunmuyor; değişimi açıklıyor. Oluşçu görüşü veren A seçeneğini işaretliyoruz.', [('Sürekli değişme','evrendeki varlıkların sürekli değişmesidir'),('Varlık: oluş süreci','oluş ve değişme süreci olarak ele alınıyor'),('Oluşçuluk','Bu görüşe oluşçuluk denir')]),
'Sosyal_Bilimler-13':('Parçadaki soruları ortak bir başlık altında toplayalım. Bilgi nedir, neyi bilebiliriz, neyi doğru sayarız ve bilgimizin sınırları nelerdir? Bunların hepsi bilgi felsefesinin konusudur. Bilgi felsefesinin diğer adı epistemolojidir. Ontoloji varlığı, estetik güzeli ve sanatı, felsefi antropoloji insanı araştırır. Burada doğrudan bilginin niteliği ve sınırları sorgulandığı için epistemolojiyi seçiyoruz. Cevap E seçeneğidir.', [('Bilgi nedir?','Bilgi nedir, neyi bilebiliriz'),('Doğruluk ve sınırlar','neyi doğru sayarız ve bilgimizin sınırları nelerdir'),('Epistemoloji','Bilgi felsefesinin diğer adı epistemolojidir')]),
'Sosyal_Bilimler-14':('Bir önermenin mutlaka doğru olması gerekmez; doğru ya da yanlış değeri alabilen bir yargı bildirmesi gerekir. Seçeneklerdeki bildirme cümleleri bu özelliği taşır. D seçeneği ise, ilk filozof Tales midir diye soruyor. Soru bir yargı ileri sürmediğinden kendisine doğru veya yanlış değeri veremeyiz. İlk filozof Talestir biçiminde bir bildirim olsaydı, doğruluğunu tartışabileceğimiz bir önerme olurdu. Önerme olmayan soru cümlesini veren D seçeneğini işaretliyoruz.', [('Önerme: yargı bildirir','doğru ya da yanlış değeri alabilen bir yargı bildirmesi gerekir'),('Soru: yargı bildirmez','Soru bir yargı ileri sürmediğinden'),('D: soru cümlesi','Önerme olmayan soru cümlesini veren D seçeneğini işaretliyoruz')]),
'Sosyal_Bilimler-15':('Kantın görüşünde duyular ve akıl birlikte çalışır. Duyular, deney yoluyla bilginin ham maddesini sağlar. Akıl ise bu verileri kategorilerle düzenleyerek bilgiye dönüştürür. Dolayısıyla duyusal veri tek başına işlenmiş bilgi değildir; akıl da deneysel veriyi tamamen yok sayarak bilgi üretemez. B seçeneği, bilginin bir yönüyle deneye, diğer yönüyle akla dayandığını söylüyor. Parçanın iki unsuru birlikte kullanma düşüncesini karşılayan B seçeneğini işaretliyoruz.', [('Deney → ham madde','Duyular, deney yoluyla bilginin ham maddesini sağlar'),('Akıl → düzenleme','Akıl ise bu verileri kategorilerle düzenleyerek bilgiye dönüştürür'),('Deney + akıl → bilgi','bilginin bir yönüyle deneye, diğer yönüyle akla dayandığını söylüyor')]),
'Sosyal_Bilimler-17':('Sorudaki hadis, çevremizdeki ihtiyaç sahiplerine karşı sorumluluğu ve paylaşmayı vurguluyor. Zekât, belirli şartlarda maldan pay vermeyi içerir. İnfak, ihtiyaçları gözeterek Allah yolunda harcamayı anlatır. Sadaka da yardım ve iyilik yoluyla dayanışmayı destekler. Üçü de komşunun ve toplumun ihtiyaçlarına kayıtsız kalmama anlayışıyla ilişkilidir. Bu nedenle yalnız birini seçmeyiz; birinci, ikinci ve üçüncü birlikte doğrudur. E seçeneğini işaretliyoruz.', [('Zekât: paylaşma','Zekât, belirli şartlarda maldan pay vermeyi içerir'),('İnfak: ihtiyaçları gözetme','İnfak, ihtiyaçları gözeterek Allah yolunda harcamayı anlatır'),('Sadaka: yardımlaşma','Sadaka da yardım ve iyilik yoluyla dayanışmayı destekler')]),
'Sosyal_Bilimler-18':('Metindeki ifadelerle öncülleri eşleştirelim. İslam sanatının Allahın birliğini ve yaratılışın güzelliğini yansıtmayı amaçladığı söyleniyor. Bu, birinci öncülü destekler. Kuranın okunması ve korunmasının musikiye ve hat sanatına ilham vermesi, üçüncü öncülün manevi içerik vurgusuyla uyumludur. İkinci öncül ise estetik değerlere önem verilmediğini söylüyor. Oysa metin güzellikten, mimarlıktan ve süslemeden söz ediyor; bu öncül metinle çelişiyor. Birinci ve üçüncü öncülleri veren D seçeneğini işaretliyoruz.', [('I: birlik ve güzellik','Allahın birliğini ve yaratılışın güzelliğini yansıtmayı amaçladığı söyleniyor'),('III: manevi içerik','üçüncü öncülün manevi içerik vurgusuyla uyumludur'),('II: metne aykırı','bu öncül metinle çelişiyor')]),
'Sosyal_Bilimler-19':('Paragraf temizliğin iki yönünü birlikte anlatıyor: bedensel temizlik ve manevi arınma. Aradığımız seçenek bu iki yönü de desteklemeli. C seçeneğinde elbiseni temiz tut ifadesi bedensel temizliği, kötü şeyleri terk et ifadesi manevi arınmayı karşılıyor. Diğer seçeneklerde hesap verme, paylaşma, yardımlaşma veya ibadetten uzaklaşma konuları öne çıkıyor. İki boyutu aynı ifadede birleştiren C seçeneğini işaretliyoruz.', [('Beden: elbiseni temiz tut','elbiseni temiz tut ifadesi bedensel temizliği'),('Manevi: kötülüğü terk et','kötü şeyleri terk et ifadesi manevi arınmayı karşılıyor'),('İki boyut birlikte','İki boyutu aynı ifadede birleştiren C seçeneğini işaretliyoruz')]),
'Sosyal_Bilimler-20':('Parçadaki teşviklerin sonuçlarını değerlendirelim. Gençlerin düşüncelerini cesaretle söylemesi ve karar alması desteklendiğinde özgüvenleri gelişir; birinci öncül uygundur. Öğretmenlik, yöneticilik ve komutanlık gibi sorumluluklar toplumda önemli roller üstlenmelerini sağlar; ikinci öncül de uygundur. Bu görevler yeteneklerini kullanıp geliştirmelerine fırsat verir; üçüncü öncül de desteklenir. Böylece üç sonuç da metinden çıkarılabilir. E seçeneğini işaretliyoruz.', [('I: özgüven','özgüvenleri gelişir'),('II: toplumsal rol','toplumda önemli roller üstlenmelerini sağlar'),('III: yeteneği kullanma','yeteneklerini kullanıp geliştirmelerine fırsat verir')]),
'Sosyal_Bilimler-22':('Üç düşünürün ortak vurgusunu buluyoruz. İlk açıklamada hayal gücü, ikincide iç dünyadan gelen ilham, üçüncüde özgün fikir ve duygular öne çıkıyor. Üçü de sanatçının yeni bir şey ortaya koymasını anlatıyor. Bu ortaklık, yaratıcılık ve özgünlüktür. Yalnız dış dünyayı yansıtmak ya da kopyalamak bu açıklamaları karşılamaz; teknik süreç ve toplumsal işlev de ortak odak değildir. Sanatın yaratıcılık ve özgünlüğe dayandığını söyleyen D seçeneğini işaretliyoruz.', [('Hayal, ilham, özgün fikir','hayal gücü, ikincide iç dünyadan gelen ilham, üçüncüde özgün fikir ve duygular öne çıkıyor'),('Yeni bir şey ortaya koyma','Üçü de sanatçının yeni bir şey ortaya koymasını anlatıyor'),('Yaratıcılık ve özgünlük','Bu ortaklık, yaratıcılık ve özgünlüktür')]),
'Sosyal_Bilimler-23':('Soruda akıl yürütmenin gerektirmediği özellik aranıyor. Akıl yürütürken öncül adı verilen önermelerden hareket eder, aralarında mantıksal ilişkiler kurarak bir sonuca ulaşırız. Bu nedenle önermelere dayanma, ilişki kurma ve yöntemli düşünme gereklidir. Ancak öncüllerin mutlaka kişisel görüş olması gerekmez. Gözlemle doğrulanan bir bilgi veya genel bir önerme de öncül olabilir. Kişisel görüş kullanmak mümkün olsa bile zorunlu değildir. B seçeneğini işaretliyoruz.', [('Öncül → mantıksal sonuç','aralarında mantıksal ilişkiler kurarak bir sonuca ulaşırız'),('Kişisel görüş şart değil','öncüllerin mutlaka kişisel görüş olması gerekmez'),('Mümkün ≠ zorunlu','Kişisel görüş kullanmak mümkün olsa bile zorunlu değildir')]),
'Sosyal_Bilimler-24':('Parçada doğruluk, bilginin nesnesini olduğu gibi yansıtması biçiminde tanımlanıyor. Yani düşüncemizle gerçeklik arasında bir uygunluk arıyoruz. Bir bilginin yararlı bulunması, başkalarınca kabul edilmesi veya bir otoritece onaylanması tek başına bu uygunluğu göstermez. Tutarlılık ise önermelerin birbirleriyle çelişmemesiyle ilgilidir. Sorudaki tanımın doğrudan karşılığı, bilgi ile gerçeklik arasındaki uygunluktur. C seçeneğini işaretliyoruz.', [('Bilgi → nesnesini yansıtır','bilginin nesnesini olduğu gibi yansıtması biçiminde tanımlanıyor'),('Doğruluk: uygunluk','düşüncemizle gerçeklik arasında bir uygunluk arıyoruz'),('Tutarlılık: çelişmeme','Tutarlılık ise önermelerin birbirleriyle çelişmemesiyle ilgilidir')]),
'Sosyal_Bilimler-25':('Epikürosun aktarılan düşüncesinde ulaşılmak istenen hedef mutluluktur. Mutluluğa erişme yollarını aramamız gerektiği söylenerek eylemlerin amacı açıklanıyor. Burada evrensel bir ahlak yasasının varlığı, özgür irade veya sorumluluğun niteliği tartışılmıyor. Hangi hedefe yönelmeliyiz sorusuna, mutluluğa yönelmeliyiz cevabı veriliyor. Bu nedenle görüş, ahlaki eylemin amacı nedir sorusuna karşılık gelir. A seçeneğini işaretliyoruz.', [('Hedef: mutluluk','ulaşılmak istenen hedef mutluluktur'),('Eylemin amacı','eylemlerin amacı açıklanıyor'),('Ahlaki eylemin amacı nedir?','ahlaki eylemin amacı nedir sorusuna karşılık gelir')])
}
out=[]
for i in items:
 if i['id']=='A-Fen_Bilimleri-11':continue
 n,notes=data[i['id'][2:]]
 for txt,cue in notes:assert cue in n,(i['id'],cue)
 i.update(narration=n,segments=[n],notes=notes,source_pair_visual_review=True,academic_review=True,highlights=[])
 if i['id']=='A-Temel_Matematik-22':i['academic_note']='Artan sıra ve seçim, farklı iki rakam ve farklı iki harf olarak yorumlandı; özgün çözümle uyumlu.'
 if i['id']=='A-Fen_Bilimleri-12':i['academic_note']='Eş koşullu akış deneyinin okul düzeyi viskozite karşılaştırması varsayımı açıkça belirtildi.'
 for k in ['metadata','partner_metadata']:
  m=i[k];pg=fitz.open(p.parent/'sources'/m['pdf_dosyasi'])[m['pdf_sayfasi']-1];r=fitz.Rect(m['soru_kirpma_konumu_pt'])
  # Remove only inspected end-of-test banners, keeping every option unchanged.
  if m['soru_kimligi'] in ['B-Fen_Bilimleri-20','A-Fen_Bilimleri-20','B-Sosyal_Bilimler-20','A-Sosyal_Bilimler-20','B-Sosyal_Bilimler-25','A-Sosyal_Bilimler-25']:
   last=[w for w in pg.get_text('words',clip=r) if w[4]=='E)'];assert last
   r.y1=min(r.y1,last[0][3]+19);m['soru_kirpma_konumu_pt']=list(r)
 out.append(i)
(p/'batch05.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
print(len(out),sum(len(x['narration']) for x in out))
