import json,fitz
from pathlib import Path
p=Path(__file__).parent;items=json.loads((p/'batch06_prepared.json').read_text())
data={
23:('Yüksekliği altı yaparak o anki zamanı bulalım. Te eksi dördün karesinin eksi yarısı artı sekiz, altıya eşit. Buradan te eksi dördün karesi dört olur; te iki veya altıdır. Şekilde roket yükselirken gösterildiği için başlangıç aldığımız an ikinci saniyedir. Yere dönüşte yükseklik sıfır olur. Aynı bağıntıdan te eksi dördün karesi on altı çıkar; uçuşun sonu sekizinci saniyedir. Sekiz eksi iki, altı saniye sonra yere düşer. Tepe noktası dördüncü saniyede sekiz metredir. Bir ve üç saniye sonrası, üçüncü ve beşinci saniyelerdir. Tepe zamanına eşit uzak olduklarından iki yükseklik de yedi buçuk metredir. Üç yargı da doğru; E seçeneğini işaretliyoruz.', [('h=6 → (t−4)²=4','te eksi dördün karesi dört olur'),('t=2; yere dönüş t=8','uçuşun sonu sekizinci saniyedir'),('8−2=6; en yüksek 8','Sekiz eksi iki, altı saniye sonra yere düşer. Tepe noktası dördüncü saniyede sekiz metredir'),('h(3)=h(5)=7,5','iki yükseklik de yedi buçuk metredir')]),
24:('Eş karelerin kenarını bir birim kabul edelim. Pembe doğrunun iki ucu arasında yatayda dört, düşeyde üç birim fark var. Böylece kenarları üç ve dört olan bir dik üçgen kurarız. Pisagordan hipotenüsün karesi dokuz artı on altı, yirmi beş olur; hipotenüs beştir. Alfa açısı düşey kenarla yapılmıştır. Bu nedenle alfaya komşu dik kenar üçtür; dört değildir. Kosinüs, komşu dik kenarın hipotenüse oranıdır. Kosinüs alfa üç bölü beş çıkar. C seçeneğini işaretliyoruz.', [('Yatay 4; düşey 3','yatayda dört, düşeyde üç birim fark var'),('3²+4²=25 → 5','hipotenüsün karesi dokuz artı on altı, yirmi beş olur; hipotenüs beştir'),('cos alfa=3/5','Kosinüs alfa üç bölü beş çıkar')]),
25:('Toplam yolu bulmak için önce okul ile kütüphane arasındaki bilinmeyen uzaklığı hesaplamalıyız. Evden çıkan iki kenar sekiz ve yedi kilometre, aralarındaki açı yüz yirmi derecedir. Kosinüs teoreminde karşı kenarın karesi, diğer iki kenarın kareleri toplamından iki kenar çarpımının iki katıyla açının kosinüsünün çarpımı çıkarılarak bulunur. Yüz yirminin kosinüsü eksi yarımdır. Uzaklığın karesi, altmış dört artı kırk dokuz artı elli altı, yüz altmış dokuz olur. Uzaklık on üç kilometredir. Ali evden okula sekiz, okuldan kütüphaneye on üç, eve dönüşte yedi kilometre yürür. Toplam sekiz artı on üç artı yedi, yirmi sekiz kilometredir. D seçeneğini işaretliyoruz.', [('cos120°=−1/2','Yüz yirminin kosinüsü eksi yarımdır'),('d²=64+49+56=169','Uzaklığın karesi, altmış dört artı kırk dokuz artı elli altı, yüz altmış dokuz olur'),('d=13','Uzaklık on üç kilometredir'),('8+13+7=28','Toplam sekiz artı on üç artı yedi, yirmi sekiz kilometredir')]),
26:('Birim kareleri sayalım: dikdörtgenin yatay kenarı beş, düşey kenarı dört birim. Köşegenin karesi, beşin karesi artı dördün karesi, kırk birdir. Alfa düşeyle yapılan açı olduğundan, kotanjantı düşey kenarın yataya oranı, yani dört bölü beştir. Beta yatayla yapılan açıdır. Kosinüs beta beş bölü kök kırk bir olur. Bunun karesi yirmi beş bölü kırk bir; tersini alınca kırk bir bölü yirmi beş elde ederiz. İstenen toplam dört bölü beş ile kırk bir bölü yirmi beştir. Paydaları yirmi beşte eşitleyince pay yirmi artı kırk bir olur. Sonuç altmış bir bölü yirmi beş çıkar. A seçeneğini işaretliyoruz.', [('Kenarlar: 5 ve 4','yatay kenarı beş, düşey kenarı dört birim'),('cot alfa=4/5','kotanjantı düşey kenarın yataya oranı, yani dört bölü beştir'),('1/cos² beta=41/25','tersini alınca kırk bir bölü yirmi beş elde ederiz'),('4/5+41/25=61/25','altmış bir bölü yirmi beş çıkar')]),
27:('İkinci kesrin paydasında bir eksi sinüs iks var. Payı ve paydayı bir artı sinüs iks ile çarparak genişletelim. Paydada iki kare farkından bir eksi sinüs kare iks oluşur. Bu ifade kosinüs kare ikse eşittir. Paydaki kosinüs iksi sadeleştirince ikinci kesir, payı bir artı sinüs iks, paydası kosinüs iks olan kesre dönüşür. Bu, ilk kesrin aynısıdır. Eşit iki kesir birbirinden çıkarılınca sıfır kalır; sondaki bir ise değişmez. Verilen açık aralıkta paydalar sıfır olmadığı için işlemler geçerlidir. Sonuç bir; B seçeneğini işaretliyoruz.', [('1−sin²x=cos²x','bir eksi sinüs kare iks oluşur. Bu ifade kosinüs kare ikse eşittir'),('İki kesir eşit','Bu, ilk kesrin aynısıdır'),('Aynı−aynı+1=1','Eşit iki kesir birbirinden çıkarılınca sıfır kalır; sondaki bir ise değişmez')]),
28:('Üç kat a ce uzunluğu, iki kat be ce uzunluğuna eşit. Bu nedenle a ce ile ce be oranı ikiye üçtür. Ce, a noktasından beye giden yolun beşte ikisindedir. İks koordinatı birden on bire gidiyor; fark on. Bunun beşte ikisi dört eder. Bire dört ekleyince cenin iks koordinatı beş olur. Ye koordinatı eksi üçten ikiye gidiyor; fark beş. Bunun beşte ikisi ikidir. Eksi üçe iki ekleyince eksi bir buluruz. Ce noktası beşe eksi birdir. Koordinat toplamı beş eksi bir, dört eder. A seçeneğini işaretliyoruz.', [('AC:CB=2:3','a ce ile ce be oranı ikiye üçtür'),('xC=1+(2/5)×10=5','Bire dört ekleyince cenin iks koordinatı beş olur'),('yC=−3+(2/5)×5=−1','Eksi üçe iki ekleyince eksi bir buluruz'),('5−1=4','Koordinat toplamı beş eksi bir, dört eder')]),
29:('Orta noktanın koordinatları, uç noktaların koordinat ortalamalarıdır. A ye ekseninde olduğu için iks koordinatı sıfır, be iks ekseninde olduğu için ye koordinatı sıfırdır. Orta nokta üçe yedi olduğuna göre benin iks koordinatı altı, anın ye koordinatı on dört olur. Eksenleri altı ve on dörtte kesen doğrunun denklemini, iks bölü altı artı ye bölü on dört eşittir bir biçiminde yazabiliriz. Her terimi kırk ikiyle çarpalım: yedi iks artı üç ye eşittir kırk iki. Bu denklemi veren C seçeneğini işaretliyoruz.', [('Orta nokta: (3,7)','Orta nokta üçe yedi olduğuna göre'),('A=(0,14); B=(6,0)','benin iks koordinatı altı, anın ye koordinatı on dört olur'),('x/6+y/14=1','iks bölü altı artı ye bölü on dört eşittir bir'),('7x+3y=42','yedi iks artı üç ye eşittir kırk iki')]),
30:('Silinmiş eksenleri bulurken karelerin aralığını birim alıyoruz. Başlangıç noktası, aya iki ve beye on birim uzaklıkta olmalı. Şekilde bunu sağlayan iki yer var: anın iki kare üstü ya da iki kare sağı. İlk yerde beye uzaklık, yatay sekiz ve düşey altı birimden, altı sekiz on üçgeniyle ondur. İkinci yerde yatay altı, düşey sekiz olur ve yine on çıkar. Ye ekseni başlangıçtan geçen düşey doğrudur. İlk olasılıkta cenin ye eksenine uzaklığı iki, denin bir birimdir. İkinci olasılıkta ce ye eksenindedir; uzaklığı sıfır, deninki üçtür. İkisinde de toplam üç eder. A seçeneğini işaretliyoruz.', [('O: A noktasının 2 üstü veya sağı','anın iki kare üstü ya da iki kare sağı'),('6²+8²=10²','altı sekiz on üçgeniyle ondur'),('1. olasılık: 2+1=3','cenin ye eksenine uzaklığı iki, denin bir birimdir'),('2. olasılık: 0+3=3','uzaklığı sıfır, deninki üçtür')]),
31:('Yansımada a ce ışını, a be ile görüntüsü a be üssü arasındaki açıyı ikiye böler. Keseni ve iki ışını kullanarak oluşan büyük üçgene bakalım. Alt kesişimde iç açı, yüz seksen eksi yüz otuz sekizden kırk ikidir. Üst kesişimde ters açı nedeniyle iç açı da kırk ikidir. A noktasındaki büyük açı, yüz seksen eksi kırk iki eksi kırk iki, doksan altı derecedir. Yansıma ekseni bunu iki eş parçaya böler; her parça kırk sekiz derece olur. Alttaki küçük üçgende, kesenle a ce arasındaki iç açı yüz seksen eksi kırk iki eksi kırk sekizden doksandır. İstenen alfa, onun bütünleridir ve o da doksan derecedir. B seçeneğini işaretliyoruz.', [('Alt iç açı: 180−138=42°','Alt kesişimde iç açı, yüz seksen eksi yüz otuz sekizden kırk ikidir'),('A açısı: 180−42−42=96°','A noktasındaki büyük açı, yüz seksen eksi kırk iki eksi kırk iki, doksan altı derecedir'),('Yarı açı: 96/2=48°','her parça kırk sekiz derece olur'),('alfa=90°','İstenen alfa, onun bütünleridir ve o da doksan derecedir')]),
}
data.update({
32:('Katlamada be köşesi a ce kenarına geldiği için katlama doğrusu a de, a açısının açıortayıdır. Verilen otuz beş dereceyi ikiyle çarparsak büyük üçgenin a açısı yetmiş derece olur. A be de üçgeninde açıların toplamını kullanalım. Be açısı, yüz seksen eksi otuz beş eksi seksen, altmış beş derecedir. Bu, büyük üçgenin de be açısıdır. Şimdi büyük üçgende ce açısını bulalım: yüz seksen eksi yetmiş eksi altmış beş, kırk beş derece. C seçeneğini işaretliyoruz.', [('A=2×35°=70°','büyük üçgenin a açısı yetmiş derece olur'),('B=180−35−80=65°','Be açısı, yüz seksen eksi otuz beş eksi seksen, altmış beş derecedir'),('C=180−70−65=45°','yüz seksen eksi yetmiş eksi altmış beş, kırk beş derece')]),
33:('Merdivenin alt ucunu ortak alan iki dik üçgeni düşünelim. İkisi de yere dik ve aynı eğik doğruyu paylaşıyor; bu nedenle benzerdir. Küçük üçgenin tabanı on iki, yüksekliği beş birim. Büyük üçgenin tabanı yalnız otuz altı değildir; on iki artı otuz altı, kırk sekizdir. Büyük tabanın küçük tabana oranı kırk sekiz bölü on iki, dört eder. Yükseklikler de aynı oranda büyür. İks, dört çarpı beşten yirmi birimdir. C seçeneğini işaretliyoruz.', [('Benzer dik üçgenler','bu nedenle benzerdir'),('Büyük taban=12+36=48','on iki artı otuz altı, kırk sekizdir'),('Oran: 48/12=4','kırk sekiz bölü on iki, dört eder'),('x=4×5=20','İks, dört çarpı beşten yirmi birimdir')]),
34:('İki yansımayı sırayla uygulayalım. İks eksenine göre yansımada iks aynı kalır, ye işaret değiştirir. Ardından ye eksenine göre yansımada bu kez iks işaret değiştirir. Sonuçta iki koordinat da başlangıçtakinin ters işaretlisidir. Bu, orijin çevresinde yüz seksen derece dönmeye eşittir. İkinci bölgedeki şekil dördüncü bölgeye geçer. Sarı daire sol üste, mavi dikdörtgen sol alta gelir. Üçgen sağ altta ve aşağı bakar. En harfi sağ üsttedir; yüz seksen derece dönünce biçimi aynı görünür. Bu yer ve yönlerin hepsi D seçeneğinde vardır. D seçeneğini işaretliyoruz.', [('(x,y) → (x,−y)','İks eksenine göre yansımada iks aynı kalır, ye işaret değiştirir'),('(x,−y) → (−x,−y)','ye eksenine göre yansımada bu kez iks işaret değiştirir'),('180° dönme','orijin çevresinde yüz seksen derece dönmeye eşittir'),('Üçgen sağ altta, aşağı','Üçgen sağ altta ve aşağı bakar')]),
35:('Açıortay teoremiyle başlayalım. De ce uzunluğuna de dersek, a be bölü a ce oranı on altı bölü dedir. A be iks olduğundan a ce, iks çarpı de bölü on altı olur. Üçgende iki kenarın toplamı üçüncüden büyüktür. İks artı iks çarpı de bölü on altı, on altı artı deden büyük olmalıdır. On altıyla çarpıp ortak pozitif on altı artı de çarpanını sadeleştirince iks on altıdan büyük çıkar. En küçük tam sayı adayımız on yedidir. Bunun mümkün olduğunu da kontrol edelim: de ceyi on altı seçersek kenarlar on yedi, on yedi ve otuz iki olur; üçgen eşitsizliği sağlanır. En küçük değer on yedi, E seçeneğini işaretliyoruz.', [('AC=xd/16','a ce, iks çarpı de bölü on altı olur'),('x+xd/16 > 16+d','İks artı iks çarpı de bölü on altı, on altı artı deden büyük olmalıdır'),('x>16','iks on altıdan büyük çıkar'),('17,17,32 mümkün → 17','kenarlar on yedi, on yedi ve otuz iki olur; üçgen eşitsizliği sağlanır')]),
36:('A be de üçgeninde kosinüs teoremini kullanalım. A benin karesi, üçün karesi artı dördün karesi eksi iki çarpı üç çarpı dört çarpı kosinüs altmıştır. Kosinüs altmış yarım olduğu için dokuz artı on altı eksi on iki, on üç buluruz. De noktasındaki diğer açı yüz yirmidir. A cenin karesi için aynı teorem, iks kare artı on altı artı dört iks verir. Şimdi büyük üçgenin a köşesindeki dikliği kullanıyoruz. A be kare ile a ce karenin toplamı, hipotenüs olan iks artı üçün karesine eşittir. On üç artı iks kare artı on altı artı dört iks, iks kare artı altı iks artı dokuz eder. Sadeleştirince yirmi eşittir iki iks, dolayısıyla iks on santimetredir. D seçeneğini işaretliyoruz.', [('AB²=9+16−12=13','dokuz artı on altı eksi on iki, on üç buluruz'),('AC²=x²+16+4x','iks kare artı on altı artı dört iks verir'),('13+x²+16+4x=(x+3)²','hipotenüs olan iks artı üçün karesine eşittir'),('20=2x → x=10','yirmi eşittir iki iks, dolayısıyla iks on santimetredir')]),
37:('A be ve a ka zıt yönlü ışınlardır. Bu nedenle be a e ile e a ka açıları bütünlerdir. Bu iki açıyı ortalayan a de ve a ce arasındaki açı, yüz seksenin yarısı olan doksan derecedir. Böylece a de ce bir dik üçgendir. A e ise bu dik üçgende hipotenüse indirilen yüksekliktir. Yükseklik teoremine göre yüksekliğin karesi, hipotenüs üzerindeki iki parçanın çarpımına eşittir. İks kare, dört çarpı sekizden otuz iki olur. Uzunluk pozitif olduğundan iks kök otuz iki, yani dört kök iki santimetredir. E seçeneğini işaretliyoruz.', [('Bütünler açıortayları: 90°','yüz seksenin yarısı olan doksan derecedir'),('AE²=DE×EC','yüksekliğin karesi, hipotenüs üzerindeki iki parçanın çarpımına eşittir'),('x²=4×8=32','İks kare, dört çarpı sekizden otuz iki olur'),('x=4√2','dört kök iki santimetredir')]),
38:('Dış açıortayı a be de üçgeninde kullanıyoruz. Ce noktası bu üçgenin be de kenarının uzantısında. Dış açıortay teoremine göre a be bölü a de, be ce bölü de ceye eşittir. Be ce, on altı artı yirmi dört, kırktır. Oran kırk bölü yirmi dört, beş bölü üç olur. A beye beş ka, a deye üç ka diyelim. Dik üçgende Pisagor, yirmi beş ka kare eksi dokuz ka kare eşittir on altının karesini verir. On altı ka kare eşittir iki yüz elli altı; buradan ka dört çıkar. İstenen a be, beş çarpı dört, yirmi birimdir. A seçeneğini işaretliyoruz.', [('AB/AD=40/24=5/3','Oran kırk bölü yirmi dört, beş bölü üç olur'),('AB=5k; AD=3k','A beye beş ka, a deye üç ka diyelim'),('16k²=256 → k=4','On altı ka kare eşittir iki yüz elli altı; buradan ka dört çıkar'),('AB=5×4=20','İstenen a be, beş çarpı dört, yirmi birimdir')]),
39:('İki lambanın oluşturduğu büyük üçgenler aynı a be tabanını paylaşıyor. Tabanlar eşit olduğundan alan oranları, yükseklik oranı olan yirmi dört bölü on iki, yani ikidir. Ortak mor bölgenin alanına em diyelim. Turuncu lambanın bütün üçgeni yetmiş beş artı em, mavi lambanın bütün üçgeni yirmi beş artı em olur. Büyük alan küçük alanın iki katı: yetmiş beş artı em eşittir iki çarpı, parantez içinde yirmi beş artı em. Sağdaki parantezi açarsak elli artı iki em elde ederiz. Düzenleyince em yirmi beş çıkar. Mor alan yirmi beş birimkaredir; C seçeneğini işaretliyoruz.', [('Alan oranı=24/12=2','alan oranları, yükseklik oranı olan yirmi dört bölü on iki, yani ikidir'),('75+M=2(25+M)','yetmiş beş artı em eşittir iki çarpı, parantez içinde yirmi beş artı em'),('75+M=50+2M','elli artı iki em elde ederiz'),('M=25','Mor alan yirmi beş birimkaredir')]),
40:('Katlamada be noktası ağırlık merkezine geliyor; ağırlık merkezine ge diyelim. Katlama doğrusu üzerinde kalan a noktası beye ve geye eşit uzaklıktadır, yani a be ile a ge eşittir. Be cenin orta noktasına em dersek, ağırlık merkezi a em kenarortayını ikiye bir oranında böler. A ge, a emin üçte ikisidir. Katlama doğrusu a de, a be ile a ge ışınlarının açıortayı olduğundan a be em üçgeninde açıortay teoremini uygularız. Be de bölü de em oranı iki bölü üç olur. Be de sekiz ise de em on iki, be em yirmidir. Em orta nokta olduğu için be ce kırk olur. De ce, kırk eksi sekizden otuz iki birimdir. C seçeneğini işaretliyoruz.', [('AB=AG=(2/3)AM','A ge, a emin üçte ikisidir'),('BD/DM=2/3','Be de bölü de em oranı iki bölü üç olur'),('BD=8 → DM=12; BM=20','Be de sekiz ise de em on iki, be em yirmidir'),('DC=40−8=32','De ce, kırk eksi sekizden otuz iki birimdir')])
})
for i in items:
 n,notes=data[i['metadata']['basili_soru_numarasi']]
 for txt,cue in notes:assert cue in n,(i['id'],cue)
 i.update(narration=n,segments=[n],notes=notes,source_pair_visual_review=True,academic_review=True,highlights=[])
 for key in ['metadata','partner_metadata']:
  m=i[key]
  if m['soru_kimligi'] in ['A-Temel_Matematik-40','B-Temel_Matematik-40']:
   pg=fitz.open(p.parent/'sources'/m['pdf_dosyasi'])[m['pdf_sayfasi']-1];r=fitz.Rect(m['soru_kirpma_konumu_pt']);last=[w for w in pg.get_text('words',clip=r) if w[4]=='E)'];assert last
   r.y1=min(r.y1,last[0][3]+20);m['soru_kirpma_konumu_pt']=list(r)
(p/'batch06.json').write_text(json.dumps(items,ensure_ascii=False,indent=2))
print(len(items),sum(len(x['narration']) for x in items))
